### ISSUE TITLE
Server 1.12 crashed. Server tick loop

### ISSUE THREAD

**Issue by sofifreak** [josephcsible/Oreberries#2] opened 2017-09-11 08:29 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (backpacks16840.jar)
  LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  IELoadingPlugin (immersive-engineering.jar)
  HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  SFRCore (solar-flux-reborn.jar)
  Inventory Tweaks Coremod (inventorytweaks.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 9/11/17 10:14 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Oreberries (oreberries)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at josephcsible.oreberries.BlockOreberryBush.func_149662_c(BlockOreberryBush.java:172)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185914_p(BlockStateContainer.java:440)
	at net.minecraft.block.Block.<init>(Block.java:236)
	at net.minecraft.block.Block.<init>(Block.java:243)
	at josephcsible.oreberries.BlockOreberryBush.<init>(BlockOreberryBush.java:79)
	at josephcsible.oreberries.proxy.CommonProxy.preInit(CommonProxy.java:89)
	at josephcsible.oreberries.OreberriesMod.preInit(OreberriesMod.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@710b30ef from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 44 more
Caused by: java.lang.RuntimeException: Attempted to load class bhz for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3328299464 bytes (3174 MB) / 3944742912 bytes (3762 MB) up to 3944742912 bytes (3762 MB)
	JVM Flags: 2 total; -Xmx4G -Xms4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 89 mods loaded, 88 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (server.jar) 
	UCH	forge{14.21.1.2443} [Minecraft Forge] (server.jar) 
	UCH	backpacks16840{3.3.2} [Backpacks!] (backpacks16840.jar) 
	UCH	versionchecker{1.3.0} [Version Checker] ([1.12] VersionChecker-1.3.0.jar) 
	UCH	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.12-4.4.4.jar) 
	UCH	baubles{1.5.1} [Baubles] (baubles.jar) 
	UCH	betterunderground{1.0.0} [Better Underground] (betterunderground-1.0.0.jar) 
	UCH	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.12-1.5.1.jar) 
	UCH	codechickenlib{3.1.2.297} [CodeChicken Lib] (codechickenlib.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	brandonscore{2.3.2} [Brandon's Core] (brandons-core.jar) 
	UCH	cavern{1.10.1} [Cavern] (cavern.jar) 
	UCH	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCH	chisel{MC1.12-0.0.13.15} [Chisel] (Chisel-MC1.12-0.0.13.15.jar) 
	UCH	chiselsandbits{14.7} [Chisels & Bits] (chiselsandbits-14.7.jar) 
	UCH	shadowmc{3.8.0} [ShadowMC] (ShadowMC-1.12-3.8.0.jar) 
	UCH	clipboard{@VERSION@} [Clipboard] (Clipboard-1.12-1.3.0.jar) 
	UCH	cofhcore{4.3.4} [CoFH Core] (cofhcore.jar) 
	UCH	cofhworld{1.0.1} [CoFH World] (cofhworld.jar) 
	UCH	customnpcs{1.12} [CustomNPCs] (custom-npcs.jar) 
	UCH	defiledlands{0.3.0} [Defiled Lands] (defiledlands-1.12.1-0.3.0.jar) 
	UCH	discordchat{2.2.1} [Discord Chat] (discordchat.jar) 
	UCH	dldungeonsjdg{1.9.3} [Doomlike Dungeons] (DoomlikeDungeons-1.9.3-MC1.12.jar) 
	UCH	draconicevolution{2.3.3} [Draconic Evolution] (draconic-evolution.jar) 
	UCH	enderore{1.12-b1} [Ender Ore] (Ender Ore-1.12-b2.jar) 
	UCH	jei{4.7.8.94} [Just Enough Items] (jei_1.12.1-4.7.8.94.jar) 
	UCH	mantle{1.12-1.3.1.18} [Mantle] (mantle.jar) 
	UCH	tconstruct{1.12-2.7.2.19} [Tinkers' Construct] (tconstruct.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.1.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCH	gottschcore{1.1.2} [GottschCore] (gottschcore.jar) 
	UCH	fastladder{1.0.6} [FastLadder!] (FastLadder-mc1.12-v1.0.6.jar) 
	UCH	ic2{2.8.16-ex112} [IndustrialCraft 2] (ic2.jar) 
	UCH	natura{1.12-4.3.0.17} [Natura] (natura.jar) 
	UCH	forestry{5.5.5.191} [Forestry] (forestry_1.12.1-5.5.5.191.jar) 
	UCH	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCH	gardenstuff{1.12-2.1.0} [Garden Stuff] (GardenStuff-1.12-2.1.0.jar) 
	UCH	goldcauldron{1.1} [Gold Cauldron] (goldcauldron-1.1.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	hammercore{1.9.4.0} [Hammer Core] (HammerCore-1.12-1.9.4.0.jar) 
	UCH	harvestcraft{1.12.1b} [Pam's HarvestCraft] (harvestcraft.jar) 
	UCH	hopperducts{1.5} [Hopper Ducts] (hopperducts-mc1.12-1.5.jar) 
	UCH	immersiveengineering{0.12-71} [Immersive Engineering] (immersive-engineering.jar) 
	UCH	immersivetech{1.3.1} [Immersive Tech] (immersivetech-1.12-1.3.1.jar) 
	UCH	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCH	teslacorelib{1.0.8} [Tesla Core Lib] (tesla-core-lib.jar) 
	UCH	industrialforegoing{1.12-1.12} [Industrial Foregoing] (industrial-foregoing.jar) 
	UCH	inventorytweaks{1.63+beta.108.6ff67c4} [Inventory Tweaks] (inventorytweaks.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	jehc{1.3.0} [Just Enough HarvestCraft] (jehc-1.12-1.3.0.jar) 
	UCH	journeymap{1.12-5.5.0b3} [JourneyMap] (journeymap.jar) 
	UCH	lostcities{1.0.0} [The Lost Cities] (lostcities-1.12-1.0.0.jar) 
	UCH	lostsouls{1.0.0} [Lost Souls] (lostsouls-1.12-1.0.0.jar) 
	UCH	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCH	refinedstorage{1.5.18} [Refined Storage] (refinedstorage-1.5.18.jar) 
	UCH	moartinkers{0.5.4} [Moar Tinkers] (moartinkers.jar) 
	UCH	nei{${mod_version}} [Not Enough Items] (nei.jar) 
	UCH	nex{2.1.11.12} [NetherEx] (NetherEx-1.12-2.1.11.12.jar) 
	UCH	openglider{@VERSION@} [Open Glider] (open-glider.jar) 
	UCE	oreberries{0.1.0} [Oreberries] (oreberries-1.12.x-0.1.0.jar) 
	UCH	plants{1.2.0} [Plants] (Plants-1.12-1.2.0(1).jar) 
	UCH	reborncore{3.2.5.88} [Reborn Core] (reborncore.jar) 
	UCH	rebornstorage{1.0.0} [RebornStorage] (rebornstorage.jar) 
	UCH	redstonepaste{1.7.5} [Redstone Paste] (redstonepaste-mc1.12-1.7.5.jar) 
	UCH	refinedstorageaddons{0.1.1} [Refined Storage Addons] (refinedstorageaddons-0.1.1.jar) 
	UCH	rftools{6.13} [RFTools] (rftools.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCH	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCH	ruins{16.7} [Ruins Mod] (Ruins-1.12.jar) 
	UCH	signpost{1.05.5} [Sign Post] (signpost.jar) 
	UCH	simplecorn{2.3.2} [Simple Corn] (SimpleCorn1.12-2.3.2.jar) 
	UCH	simplequarry{1.0.7} [Simple Quarry] (SimpleQuarry-1.12-1.0.7.jar) 
	UCH	simplebedrolls{1.2.1} [Simple Bedrolls] (simply-bedrolls.jar) 
	UCH	simulatednights{1.12-2.1.0} [Simulated Nights] (simulatednights-1.12-2.1.0.jar) 
	UCH	solarfluxreborn{3.25r} [Solar Flux Reborn] (solar-flux-reborn.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCH	subcommonlib{1.2.0.1} [Subaraki's Common Library] (subcommonlib-sublib-1.12-1.2.0.1.jar) 
	UCH	telepads{1.11.2-1.0.2.1} [Telepads] (telepads.jar) 
	UCH	thermalfoundation{2.3.4} [Thermal Foundation] (thermalfoundation.jar) 
	UCH	thermaldynamics{2.3.4} [Thermal Dynamics] (thermaldynamics.jar) 
	UCH	thermalexpansion{5.3.4} [Thermal Expansion] (thermalexpansion.jar) 
	UCH	waystones{4.0.15} [Waystones] (waystones.jar) 
	UCH	teslacorelib_registries{1.0.8} [Tesla Core Lib Registries] (tesla-core-lib.jar) 
	UD	solarfluxreborncore{3.25r} [Solar Flux Reborn: Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (backpacks16840.jar)
  brad16840.common.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.12-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
IELoadingPlugin (immersive-engineering.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
HammerCoreCore (HammerCore-1.12-1.9.4.0.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
LoadingPlugin ([1.12] VersionChecker-1.3.0.jar)
  
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  team.chisel.ctm.client.asm.CTMTransformer
SFRCore (solar-flux-reborn.jar)
  com.pengu.solarfluxreborn.core.SFRSerializedTransformer
Inventory Tweaks Coremod (inventorytweaks.jar)
  invtweaks.forge.asm.ContainerTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by josephcsible** [comment] 2017-09-11 11:08
Duplicate of #1, already fixed in the latest version.

**Closed as completed by josephcsible** 2017-09-11 11:08 UTC
